apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: myservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myservice
  template:
    metadata:
      labels:
        app: myservice
    spec:
      containers:
      - name: frontend
        image: frontt
        lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
