version: '3'

services:
  frontend:
    build: frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
        - ./frontend:/frontend
  backend:
    build: Backend
    ports:
      - 8000:80
    volumes:
      - ./Backend:/Backend
